config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "/blog_posts/my_posts", to:"blog_posts#my_posts", as: :my_posts
  resources :blog_posts do
    resource :cover_image, only: [:destroy], module: :blog_posts
  end 
  
  # get "/blog_posts/new", to:"blog_posts#new",  as: :new_blog_post
  # get "/blog_posts/:id", to:"blog_posts#show",  as: :blog_post
  # get "/blog_posts/:id/edit" , to: "blog_posts#edit" , as: :edit_blog_post
  # patch "/blog_posts/:id" , to:"blog_posts#update" 
  # delete "/blog_posts/:id", to:"blog_posts#destroy"
  # post "/blog_posts" , to:"blog_posts#create" , as: :blog_posts
  
  # Defines the root path route ("/")
  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
    has_one_attached :cover_image
    has_rich_text :content

    validates :title, presence: true
    validates :content, presence: true

    scope :sorted, ->{order(arel_table[:published_at].desc.nulls_last).order(updated_at: :desc)}
    scope :draft, -> {where(published_at: nil)}
    scope :published, -> {where("published_at <= ?", Time.current)}
    scope :scheduled, -> {where("published_at > ?", Time.current)}

    def draft?
        published_at.nil?
    end

    def published?
        published_at? && published_at <= Time.current
    end

    def scheduled?
        published_at? && published_at > Time.current
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts/cover_images_controller.rb
class BlogPosts::CoverImagesController < ApplicationController
    include ActionView::RecordIdentifier

    before_action :authenticate_user!
    before_action :set_blog_post

    def destroy
        @blog_post.cover_image.purge_later
        # redirect_to edit_blog_post_path(@blog_post)
        respond_to do |format|
            format.html { redirect_to edit_blog_post_path(@blog_post)}
            format.turbo_stream {render turbo_stream: turbo_stream.remove(dom_id(@blog_post, :cover_image)) }
        end
    end

    def set_blog_post
        @blog_post = BlogPost.find(params[:blog_post_id])
    end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show] 
    before_action :set_blog_post, only: [:show,:update,:destroy]

    def index
        # @blog_posts = user_signed_in? ? BlogPost.where(creator_id: current_user.id)
        # .or(BlogPost.published)
        # .sorted :  BlogPost.published.sorted
        @blog_posts = BlogPost.published.sorted
    end

    # get a specific blog
    def show 
    end

    def my_posts
        @blog_posts = BlogPost.where(creator_id: current_user.id).sorted
    end

    # gives the form in view
    def new
        @blog_post = BlogPost.new
    end

    # post request to store in db
    def create
        @blog_post = BlogPost.new(blog_post_params)
        @blog_post.creator_id = current_user.id

        if @blog_post.save
            redirect_to @blog_post
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @blog_post = BlogPost.find(params[:id])
        if @blog_post.creator_id != current_user.id
            redirect_to @blog_post, alert: "You are not authorized to edit this post", status: :unauthorized
        end
    end

    def update
        # @blog_post = BlogPost.find(params[:id])
        if @blog_post.update(blog_post_params)
            redirect_to @blog_post
        else
            render :edit , status: :unprocessable_entity
        end
    end

    def destroy
        # @blog_post = BlogPost.find(params[:id])
        @blog_post.destroy
        redirect_to root_path
    end

    # a helper function to permit the params to put in database
    def blog_post_params
        params.require(:blog_post).permit(:title,:content,:published_at,:cover_image)
    end

    def set_blog_post
        @blog_post = user_signed_in? ? BlogPost.find(params[:id]) :BlogPost.published.find(params[:id])
        # @blog_post = user_signed_in? ? BlogPost.where(creator_id: current_user.id).find(params[:id]) :BlogPost.published.find(params[:id])

        # redirect the request
        rescue ActiveRecord::RecordNotFound
            redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_form.html.erb
<%= form_with model: blog_post do |form|%>
    <% if form.object.errors.any? %>
        <div>
            <% form.object.errors.full_messages.each do |message|%>
                <div class="text-red-400"> <%= message%> </div>
            <%end%>
        </div>
    <% end %>

    <div class="mb-5 flex flex-col">
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <% if blog_post.cover_image.present? %>
        <div id="<%= dom_id(blog_post, :cover_image) %>" class="flex items-center">
            <%= image_tag blog_post.cover_image, class: "w-1/4" %>
            <%= link_to "remove", blog_post_cover_image_path(blog_post), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
        </div>
    <%end%>

    <div class="mb-5 flex flex-col">
        <%= form.label :cover_image %>
        <div>
            <%= form.file_field :cover_image%>
        </div>
        
    </div>

    <div  class="mb-5 flex flex-col">
        <%= form.label :content %>
        <%= form.rich_text_area :content %>
    </div>

    <div class="mb-5">
        <%= form.label :published_at %>
        <%= form.datetime_select :published_at, include_blank: true%>
    </div>

    <%= form.button :submit ,class: "btn-primary"%>
<%end%>

app/views/blog_posts/edit.html.erb
<h1>Edit blog post</h1>

<%# a partial to reuse a component%>
<%= render partial:"form" , locals: {blog_post: @blog_post}%>

<%= button_to "Delete", @blog_post, method: :delete, data: {turbo_confirm: "Are you sure?"} %>

app/views/blog_posts/index.html.erb
<h1>Blog app</h1>

<% @blog_posts.each do |blog_post|%>
    <h2 class="text-sm text-red-600 mb-0"><%= link_to blog_post.title , "#{blog_post_path(blog_post)}" %></h2>
    <% if blog_post.draft? %>
        <div class="p-1 bg-gray-100 rounded">Draft</div>
    <%end%>    
    <% if blog_post.scheduled? %>
        <div class="p-1 bg-blue-100 rounded">Scheduled</div>
    <%end%>    

    <p><%= blog_post.content%></p>
<% end %>

app/views/blog_posts/my_posts.html.erb
<div class="flex justify-end items-center">
    <span class="mr-2">Filter:</span>
    <select id="filter-select">
        <option value="all" <%= params[:filter] == 'all' ? 'selected' : '' %>>All</option>
        <option value="drafts" <%= params[:filter] == 'drafts' ? 'selected' : '' %>>Drafts</option>
        <option value="published" <%= params[:filter] == 'published' ? 'selected' : '' %>>Published</option>
        <option value="scheduled" <%= params[:filter] == 'scheduled' ? 'selected' : '' %>>Scheduled</option>
    </select>
</div>

<% filtered_posts = @blog_posts %>
<% case params[:filter]
    when "all"
     filtered_posts = filtered_posts
   when "drafts"
     filtered_posts = filtered_posts.select { |post| post.draft? }
   when "published"
     filtered_posts = filtered_posts.select { |post| post.published? }
   when "scheduled"
     filtered_posts = filtered_posts.select { |post| post.scheduled? }
   end %>

<% filtered_posts.each do |blog_post| %>
    <h2 class="text-sm text-red-600 mb-0"><%= link_to blog_post.title , "#{blog_post_path(blog_post)}" %></h2>
    <% if blog_post.draft? %>
        <div class="p-1 bg-gray-100 rounded">Draft</div>
    <% elsif blog_post.scheduled? %>
        <div class="p-1 bg-blue-100 rounded">Scheduled</div>
    <% end %>
    <p><%= blog_post.content %></p>
<% end %>

<script>
    document.getElementById("filter-select").addEventListener("change", function(){
        var filter = this.value;
        var url = new URL(window.location.href);
        url.searchParams.set("filter", filter);
        window.location.href = url;
    });
</script>

app/views/blog_posts/new.html.erb
<h1>Create new blog</h1>

<%# a partial to reuse a component%>
<%= render partial: "form" , locals: {blog_post: @blog_post} %>

app/views/blog_posts/show.html.erb
<% if user_signed_in? && current_user.id == @blog_post.creator_id %>
  <%= link_to "Edit", edit_blog_post_path(@blog_post) , class: "text-blue-500"%>
<% end %>

<%= image_tag @blog_post.cover_image if @blog_post.cover_image.present?%>
<h1><%= @blog_post.title %></h1>
<%= @blog_post.content %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="prose m-auto">
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="mb-5 flex">
      <%= link_to "Home" , root_path, class: "text-blue-500"%>
      
      <% if user_signed_in? %>
        <%= link_to "My posts" , my_posts_path , class: "ml-3 text-blue-500"%>
        <%= link_to "New blog" , new_blog_post_path, class: "ml-3 text-blue-500"%>
        <%= link_to "Profile", edit_user_registration_path, class:"ml-3 text-blue-500 mr-auto"%>
        <%= button_to "Logout", destroy_user_session_path , method: :delete, class: "btn-primary"%>
      <% else %>
        <%= link_to "Login" , new_user_session_path, class: "ml-3 text-blue-500" %>
        <%= link_to "Sign up" , new_user_registration_path, class: "ml-3 text-blue-500" %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>